'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { RasaChatbotWidget as RasaChatbotWidgetElement, defineCustomElement as defineRasaChatbotWidget } from "@rasahq/chat-widget-ui/dist/components/rasa-chatbot-widget.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type RasaChatbotWidgetEvents = {
    onChatSessionStarted: EventName<CustomEvent<{ sessionId: string }>>,
    onChatWidgetReceivedMessage: EventName<CustomEvent<unknown>>,
    onChatWidgetSentMessage: EventName<CustomEvent<string>>,
    onChatWidgetQuickReply: EventName<CustomEvent<string>>,
    onChatWidgetOpened: EventName<CustomEvent<undefined>>,
    onChatWidgetClosed: EventName<CustomEvent<undefined>>,
    onChatWidgetHyperlinkClicked: EventName<CustomEvent<undefined>>,
    onChatWidgetFileStartedDownload: EventName<CustomEvent<undefined>>
};

const RasaChatbotWidget: StencilReactComponent<RasaChatbotWidgetElement, RasaChatbotWidgetEvents> = /*@__PURE__*/ createComponent<RasaChatbotWidgetElement, RasaChatbotWidgetEvents>({
    tagName: 'rasa-chatbot-widget',
    elementClass: RasaChatbotWidgetElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChatSessionStarted: 'chatSessionStarted',
        onChatWidgetReceivedMessage: 'chatWidgetReceivedMessage',
        onChatWidgetSentMessage: 'chatWidgetSentMessage',
        onChatWidgetQuickReply: 'chatWidgetQuickReply',
        onChatWidgetOpened: 'chatWidgetOpened',
        onChatWidgetClosed: 'chatWidgetClosed',
        onChatWidgetHyperlinkClicked: 'chatWidgetHyperlinkClicked',
        onChatWidgetFileStartedDownload: 'chatWidgetFileStartedDownload'
    } as RasaChatbotWidgetEvents,
    defineCustomElement: defineRasaChatbotWidget
});

export default RasaChatbotWidget;
